services:
  redis:
    image: redis:7.4.2
    restart: unless-stopped
    ports:
      - '127.0.0.1:6482:6379'
    volumes:
      - redis:/data
  postgres:
    image: postgres:17
    restart: unless-stopped
    ports:
      - 127.0.0.1:5759:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gpr_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - '127.0.0.1:1025:1025'  # SMTP port
      - '127.0.0.1:8025:8025'  # Web UI port
    volumes:
      - mailpit_data:/data
volumes:
  redis:
    driver: local
  postgres_data:
    driver: local
  mailpit_data:
    driver: local
