// Generated by ai

import MainLayout from '../layouts/MainLayout'
import { Box, Typography, Button, Container, Paper, keyframes, Chip, Grid } from '@mui/material'
import ErrorOutlineIcon from '@mui/icons-material/ErrorOutline'
import SentimentVeryDissatisfiedIcon from '@mui/icons-material/SentimentVeryDissatisfied'
import ExploreOffIcon from '@mui/icons-material/ExploreOff'
import PetsIcon from '@mui/icons-material/Pets'
import CoffeeIcon from '@mui/icons-material/Coffee'
import { useNavigate } from 'react-router-dom'
import { useState, useEffect } from 'react'

// Define keyframes for the wobble animation
const wobble = keyframes`
  0% { transform: rotate(0deg) scale(1); }
  25% { transform: rotate(5deg) scale(1.05); }
  50% { transform: rotate(-5deg) scale(0.95); }
  75% { transform: rotate(5deg) scale(1.05); }
  100% { transform: rotate(0deg) scale(1); }
`

const float = keyframes`
  0% { transform: translateY(0px); }
  50% { transform: translateY(-10px); }
  100% { transform: translateY(0px); }
`

const excuses = [
  'The page is on a coffee break',
  'This page is playing hide and seek',
  '404: Page went on vacation',
  'Our hamsters lost this page',
  'The page was eaten by zombies',
  'This link has gone fishing',
  'This URL took a wrong turn',
]

export default function NotFound() {
  const navigate = useNavigate()
  const [excuse, setExcuse] = useState(excuses[0])

  // Change excuse every 3 seconds
  useEffect(() => {
    const interval = setInterval(() => {
      const randomIndex = Math.floor(Math.random() * excuses.length)
      setExcuse(excuses[randomIndex])
    }, 3000)

    return () => clearInterval(interval)
  }, [])

  return (
    <MainLayout>
      <Container maxWidth="md" sx={{ textAlign: 'center', py: 8 }}>
        <Paper
          elevation={3}
          sx={{
            p: 5,
            borderRadius: 4,
            background: 'linear-gradient(145deg, #f0f0f0, #e6e6e6)',
            position: 'relative',
            overflow: 'hidden',
          }}>
          {/* Decorative elements */}
          <Box
            sx={{
              position: 'absolute',
              top: 20,
              left: 20,
              animation: `${float} 3s infinite ease-in-out`,
              opacity: 0.5,
              color: 'primary.light',
              fontSize: '2rem',
            }}>
            <ExploreOffIcon fontSize="inherit" />
          </Box>

          <Box
            sx={{
              position: 'absolute',
              bottom: 20,
              right: 20,
              animation: `${float} 4s infinite ease-in-out`,
              opacity: 0.5,
              color: 'secondary.light',
              fontSize: '2rem',
            }}>
            <PetsIcon fontSize="inherit" />
          </Box>

          <Box
            sx={{
              fontSize: '8rem',
              color: 'primary.main',
              mb: 2,
              animation: `${wobble} 2s infinite`,
            }}>
            <SentimentVeryDissatisfiedIcon fontSize="inherit" />
          </Box>

          <Typography variant="h2" gutterBottom fontWeight="bold" sx={{ color: 'error.main' }}>
            404
          </Typography>

          <Typography variant="h4" gutterBottom>
            Oops! Page Not Found
          </Typography>

          <Typography variant="body1" color="text.secondary" sx={{ mb: 4, maxWidth: '80%', mx: 'auto' }}>
            Looks like you've ventured into uncharted territory. The page you're looking for has gone on vacation or
            never existed in the first place!
          </Typography>

          <Chip label={excuse} color="secondary" icon={<CoffeeIcon />} sx={{ mb: 4 }} />

          <Grid container spacing={2} justifyContent="center">
            <Grid size={6}>
              <Button
                size="large"
                variant="contained"
                onClick={() => navigate('/dashboard')}
                startIcon={<ErrorOutlineIcon />}
                sx={{
                  borderRadius: 2,
                  '&:hover': {
                    transform: 'scale(1.05)',
                  },
                  transition: 'transform 0.2s',
                }}>
                Back to Safety
              </Button>
            </Grid>
            <Grid size={6}>
              <Button
                size="large"
                variant="outlined"
                onClick={() => window.history.back()}
                sx={{
                  borderRadius: 2,
                  '&:hover': {
                    transform: 'scale(1.05)',
                  },
                  transition: 'transform 0.2s',
                }}>
                Go Back
              </Button>
            </Grid>
          </Grid>
        </Paper>
      </Container>
    </MainLayout>
  )
}
